# Generated by Django 6.0.3 on 2026-05-15 15:39

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Số điện thoại')),
                ('role', models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('EMPLOYER', 'Nhà tuyển dụng'), ('CANDIDATE', 'Ứng viên')], default='CANDIDATE', max_length=20, verbose_name='Vai trò người dùng')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Trạng thái xác minh (Admin duyệt)')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Lý do từ chối duyệt')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='Thư giới thiệu/Lời nhắn')),
                ('employers_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú của nhà tuyển dụng')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Nhà tuyển dụng chấm điểm sau khi xem hồ sơ hoặc phỏng vấn', null=True, verbose_name='Đánh giá chất lượng (1-5 sao)')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('reviewed', 'Đã xem hồ sơ'), ('interviewing', 'Đang phỏng vấn'), ('accepted', 'Trúng tuyển'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái đơn ứng tuyển')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nộp đơn')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Công ty',
                'verbose_name_plural': 'Công ty',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('benefits', models.TextField(blank=True)),
                ('salary_min', models.BigIntegerField(blank=True, null=True)),
                ('salary_max', models.BigIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('experience_level', models.CharField(choices=[('no_exp', 'Chưa có kinh nghiệm'), ('1_year', '1 năm kinh nghiệm'), ('2_years', '2 năm kinh nghiệm'), ('senior', 'Trên 5 năm kinh nghiệm')], default='no_exp', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Số lượt xem tin')),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'job_category',
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to=models.Q(('candidate_profile__isnull', True), ('role', 'CANDIDATE')), on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidate_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa điểm')),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vị trí mong muốn')),
                ('summary', models.TextField(blank=True, max_length=500, null=True, verbose_name='Giới thiệu bản thân ngắn gọn')),
                ('is_looking_for_job', models.BooleanField(default=True, verbose_name='Đang tìm việc')),
                ('cv_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Tập tin CV (PDF/Word)')),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidate_profile',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user', models.OneToOneField(limit_choices_to=models.Q(('employer_profile__isnull', True), ('role', 'EMPLOYER')), on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('500+', '500+')], max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức vụ')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='apps.company')),
            ],
            options={
                'verbose_name': 'Hồ sơ Nhà tuyển dụng',
                'db_table': 'employer_profiles',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('location', models.CharField(max_length=255, verbose_name='Địa điểm/Link họp')),
                ('interview_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú phỏng vấn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='apps.application', verbose_name='Đơn ứng tuyển')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='apps.job', verbose_name='Công việc ứng tuyển'),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='apps.jobcategory'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung thông báo')),
                ('notification_type', models.CharField(choices=[('application_update', 'Cập nhật ứng tuyển'), ('interview_invite', 'Mời phỏng vấn'), ('job_recommendation', 'Gợi ý việc làm'), ('employer_verify', 'Xác minh NTD'), ('new_application', 'Ứng tuyển mới'), ('system', 'Hệ thống')], default='system', max_length=25)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='apps.candidateprofile', verbose_name='Ứng viên'),
        ),
        migrations.AddField(
            model_name='job',
            name='Employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='apps.employer'),
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày lưu')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_candidates', to='apps.job', verbose_name='Công việc')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='apps.candidateprofile', verbose_name='Ứng viên')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('candidate', 'job')},
        ),
    ]
