# Generated by Django 6.0.3 on 2026-05-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_employer_job_employer_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_preset',
            field=models.BooleanField(default=False, verbose_name='Công ty có sẵn'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
