# Generated by Django 6.0.3 on 2026-05-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_company_is_preset_alter_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Người đại diện'),
        ),
    ]
