# Generated by Django 6.0.3 on 2026-05-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_employer_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='title',
        ),
    ]
