# Generated by Django 6.0.3 on 2026-05-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_candidateprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='cv_file',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn file CV'),
        ),
    ]
