# Generated by Django 6.0.3 on 2026-05-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_candidateprofile_cv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='cv_file',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Bổ sung'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='education',
            field=models.TextField(blank=True, verbose_name='Học vấn'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Kinh nghiệm'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Kỹ năng'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, null=True, verbose_name='Thư giới thiệu'),
        ),
        migrations.AlterField(
            model_name='application',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Đánh giá (1-5 sao)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('reviewed', 'Đã xem hồ sơ'), ('interviewing', 'Đang phỏng vấn'), ('accepted', 'Trúng tuyển'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
