# Generated by Django 6.0.3 on 2026-05-22 15:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_candidateprofile_cv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Giới thiệu bản thân'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
