# Generated by Django 6.0.3 on 2026-05-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_verificationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
