# Generated by Django 6.0.3 on 2026-05-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_job_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rejection_reason',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
