# Generated by Django 6.0.3 on 2026-05-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_remove_employer_company_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Hồ sơ ứng tuyển', 'verbose_name_plural': 'Hồ sơ ứng tuyển'},
        ),
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'verbose_name': 'Hồ sơ ứng viên', 'verbose_name_plural': 'Hồ sơ ứng viên'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Hồ sơ Nhà tuyển dụng', 'verbose_name_plural': 'Hồ sơ Nhà tuyển dụng'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'công việc', 'verbose_name_plural': 'công việc'},
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name': 'Ngành nghề', 'verbose_name_plural': 'Ngành nghề'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
    ]
